name: BE, FE & Mock DB Connection

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }} # test varioous node versions

      - name: Install dependencies in app directory # check if dependencies are okay
        run: npm install
        working-directory: app

      - name: Install dependencies in backend directory # check if dependencies are okay
        run: npm install
        working-directory: backend

      - name: Start application # run the application in build mode
        run: npm run build
        env:  
          CI: false
        working-directory: app


      - name: Start backend # run a mock MongoDB Connection
        run: npm test
        working-directory: backend

