name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies in app directory
        run: npm install
        working-directory: app

      - name: Install dependencies in backend directory
        run: npm install
        working-directory: backend

      - name: Start application
        run: |
          npm start
          if [ $? -eq 0 ]; then
            echo "npm start completed successfully"
          else
            echo "npm start failed" >&2
            exit 1
          fi
        working-directory: app

      - name: Start backend
        run:  |
          npm start
          if [ $? -eq 0 ]; then
            echo "npm start completed successfully"
          else
            echo "npm start failed" >&2
            exit 1
          fi
        working-directory: backend

