name: Build and Push Docker Image

on:
  workflow_run:
    workflows: ["Initialization of BE & FE, and Mock Database Connection"]
    # branches: [main]
    types:
        - completed

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          push: true
          tags: frontend:latest
      -
        name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
            context: ./backend
            push: true
            tags: server:latest
      -
        name: Build and push database image
        uses: docker/build-push-action@v5
        with:
            context: ./backend
            push: true
            tags: mongo:latest